#!/bin/sh

set -e

zcat /usr/share/doc/perfsonar-meshconfig-jsonbuilder/examples/example.json.gz \
| sed '/include/,+2{d}' \
| /usr/lib/perfsonar/bin/validate_configuration --config_url=file:///dev/stdin
