#!/bin/sh

set -e

zcat /usr/share/doc/perfsonar-meshconfig-jsonbuilder/examples/example.json.gz \
| sed '/include/,+2{d}' \
| /usr/lib/perfsonar/bin/validate_json --config_url=file:///dev/stdin --output=- \
| grep -A 10 host_classes
