#!/bin/sh

set -e

sed '/include/,+2{d}' /usr/share/doc/perfsonar-meshconfig-jsonbuilder/examples/example.json \
| /usr/lib/perfsonar/bin/validate_json --config_url=file:///dev/stdin --output=- \
| grep -A 10 host_classes
