bin/generate_configuration usr/lib/perfsonar/bin
doc/cron-restart_services usr/share/doc/perfsonar-meshconfig-agent/examples/
etc/meshconfig-agent.conf etc/perfsonar/
lib/perfSONAR_PS/MeshConfig/Agent.pm usr/share/perl5/perfSONAR_PS/MeshConfig
lib/perfSONAR_PS/MeshConfig/Generators/perfSONARRegularTesting.pm usr/share/perl5/perfSONAR_PS/MeshConfig/Generators
scripts/perfsonar-meshconfig-agent etc/cron.d/
