etc/meshconfig-agent.conf etc/perfsonar/
etc/meshconfig-agent-logger.conf etc/perfsonar/
etc/meshconfig-agent-tasks.conf usr/share/doc/perfsonar-meshconfig-agent/examples/
bin/perfsonar_meshconfig_agent usr/lib/perfsonar/bin
lib/perfSONAR_PS/MeshConfig/Agent.pm usr/share/perl5/perfSONAR_PS/MeshConfig
lib/perfSONAR_PS/MeshConfig/Generators/perfSONARRegularTesting.pm usr/share/perl5/perfSONAR_PS/MeshConfig/Generators
