etc/meshconfig-guiagent.conf etc/perfsonar/
etc/meshconfig-guiagent-logger.conf etc/perfsonar/
bin/perfsonar_meshconfig_guiagent usr/lib/perfsonar/bin
lib/perfSONAR_PS/MeshConfig/GUIAgent.pm usr/lib/perfsonar/lib/perfSONAR_PS/MeshConfig
lib/perfSONAR_PS/MeshConfig/Generators/MaDDash usr/lib/perfsonar/lib/perfSONAR_PS/MeshConfig/Generators
lib/perfSONAR_PS/MeshConfig/Generators/MaDDash.pm usr/lib/perfsonar/lib/perfSONAR_PS/MeshConfig/Generators
